# GCP Configuration for OpenImpactCascade
# Generated by Terraform on ${timestamp()}
# DO NOT COMMIT THIS FILE TO VERSION CONTROL

# GCP Project Configuration
GOOGLE_CLOUD_PROJECT=${project_id}
GCP_REGION=${region}

# Vertex AI RAG Configuration
VERTEX_RAG_CORPUS=${corpus_name}
VERTEX_RAG_GCS_BUCKET=${bucket_name}

# Service Account
GOOGLE_APPLICATION_CREDENTIALS=${key_path}

# Application Configuration (add your keys)
# ANTHROPIC_API_KEY=your-anthropic-key-here
# SECRET_KEY=your-flask-secret-here
